project:
  type: website
  output-dir: docs

website:
  title: "Rice Stock Market Data Portal Guide"
  description: "User Guide for Rice Business Stock Market Data Portal"
  page-footer:
    left: "© Kerry Back"
  

format:
  html:
    theme: 
      light: [flatly, styles.css]
      dark: [superhero, styles.css]

