---
format: html
---

# User Guide for Rice Business Stock Market Data Portal

Queries are SQL (Structured Query Language) commands.  To enter a command, click on the "Execute Query" button.  Pressing the Enter key will not execute the query.

SQL is not case sensitive.  It is common to see SQL commands written in uppercase, and we will do so below, but lowercase is also accepted.  Cases matter only when referring to variables, tables, and other database objects.  Variable names must be quoted with single quotes.  Table names are not quoted.

SQL commands can be written over multiple lines.  For human readability, it is common to write different components of a command on separate lines, as you will see in the following examples.

#### Get all data from a table

```sql
SELECT * FROM table_name
```

#### Get specific columns from a table

```sql
SELECT column1, column2 FROM table_name
```

#### Get specific rows from a table

```sql
SELECT * FROM table_name WHERE condition
```

#### Get specific rows and columns from a table

```sql
SELECT column1, column2 FROM table_name 
WHERE condition
```

#### Example of conditions

```sql
WHERE ticker = 'AAPL' and date >= '2024-01-01'
```

#### Get only the first rows from a table

This is useful to get an understanding of a table structure.

```sql
SELECT * FROM table_name LIMIT 10
```

#### Get the number of rows in a table

```sql
SELECT COUNT(*) FROM table_name
```

#### Join tables

We will often want to get an industry classification from the Tickers table to combine with variables selected from another table.  This is called a join operation.  Other join operations may also be useful.  The Tickers table contains several industry and sector classifications (industry, sector, sicindustry, sicsector, famaindustry, siccode).  The "as" in the following example can be omitted.

```sql
SELECT A.ticker, A.industry, B.date, B.close
FROM tickers as A inner join sep as B on A.ticker = B.ticker
WHERE B.date = (SELECT MAX(date) FROM B)
```

#### Close and open variables in sep table

The sep table contains daily closing prices and adjusted closing prices (close and adjclose).  It also contains the open price (open).33